/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  docs: [
    'Home',
    {
      HC: ['hc/html', 'hc/css'],
      JS: [
        'js/basic',
        'js/advanced',
        'js/dataStructure',
        'js/module',
        'js/reg',
      ],
      Extension: ['extension/web-api', 'extension/browser'],
      TS: ['ts/basic'],
      React: ['react/basic', 'react/redux', 'react/hooks', 'react/core'],
      Dev: ['dev/git', 'dev/node', 'dev/os', 'dev/webpack'],
      Network: ['network/basic'],
      Algo: [
        'algo/basic',
        'algo/sort',
        'algo/sword',
        'algo/dp',
        'algo/linkedList',
        'algo/tree',
      ],
      Interview: ['interview/hand', 'interview/scene'],
      Vue: ['vue/basic'],
      // Fe  todo  downloads
    },
  ],
};
